# Generated by Django 5.0.6 on 2024-06-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="quantidade",
            field=models.IntegerField(),
        ),
    ]
